from setuptools import setup, find_packages

setup(
    name="sentiment-analysis-trading",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "requests>=2.32.3",
        "pandas>=2.2.2",
        "numpy>=1.26.4",
        "scikit-learn>=1.5.0",
        "tweepy>=4.14.0",
        "praw>=7.7.1",
        "newsapi-python>=0.2.7",
        "yfinance>=0.2.4",
        "polygon-api-client>=0.5.1",
        "alpha-vantage>=2.3.1",
        "transformers>=4.36.0",
        "torch>=2.1.2",
        "nltk>=3.8.1",
        "textblob>=0.17.1",
        "vaderSentiment>=3.3.2",
        "spacy>=3.7.2",
        "asyncio",
        "aiohttp>=3.9.1",
        "concurrent-log-handler>=0.9.20",
        "schedule>=1.2.0",
        "redis>=5.0.1",
        "python-dotenv>=1.0.0",
        "pydantic>=2.5.0",
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0",
        "pyarrow>=14.0.2",
    ],
    author="GoQunat Team",
    author_email="team@goqunat.com",
    description="High-performance sentiment analysis and trade signal generation system",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/goqunat/sentiment-analysis-trading",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
    python_requires=">=3.9",
)